---
title: "Workshop"
author: "Alice Roberts"
date: "3/26/2019"
output: html_document
---
---
title: "TSA Workshop"
author: "Alice Roberts"
date: "3/12/2019"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("xts")
library(quantmod)
library(tseries)
library(timeSeries)
library(forecast)
library(xts)

```

### Step 1 : Visualize the TS 
```{r }
# Apple Inc.
# Pull data from Yahoo finance 
getSymbols("AAPL", from = '2014-12-01', to = '2018-12-01')

# Select the relevant close price series
stock_prices <- AAPL[, 4]

#plotting the time series
plot(stock_prices)

## we can see there is an upward trend, so we need to make our data stationary. 



```


### Step 2: Stationarize the Series

```{r}

#In the next step, we compute the logarithmic returns of the stock as we want the ARIMA model to forecast the log returns and not the stock price. We also plot the log return series using the plot function.

# Compute the differenced log returns for the stock 
stock <- diff(log(stock_prices), lag = 1)

#getting rid of the missing  values 
stock <- stock[!is.na(stock)]



# Plot log returns 
plot(stock, type = 'l', main = 'log returns plot')


## our data looks more stationary here, we have a constant mean for sure. 

# to be sure we conduct the ADF test on log returns series for stationarity
print(adf.test(stock))

# we have a signifcant p-value of 0.01 thus we conclude that our time series is stationary.

```

### Step 3: Find Optimal Parameters

```{r}

# Split the dataset in two parts - training and testing
breakpoint <- floor(nrow(stock)*(3/4))

# Apply the ACF and PACF functions
par(mfrow = c(1,1))
acf.stock <- acf(stock[c(1:breakpoint),], main = 'ACF Plot', lag.max = 100)
pacf.stock <- pacf(stock[c(1:breakpoint),], main = 'PACF Plot', lag.max = 100)

```

### Step 4: Build ARIMA Model
```{r,results="hide"}

# Initialzing an xts object for Actual log returns
Actual_series <- xts(0,as.Date("2017-12-01","%Y-%m-%d"))

# Initialzing a dataframe for the forecasted return series
forecasted_series <- data.frame(Forecasted = numeric())

#Our objective is to forecast the entire returns series from breakpoint onwards. We will make use of the For Loop statement in R and within this loop we will forecast returns for each data point from the test dataset.

#In the code given below, we first initialize a series which will store the actual returns and another series to store the forecasted returns.  In the For Loop, we first form the training dataset and the test dataset based on the dynamic breakpoint.

#We call the arima function on the training dataset for which the order specified is (2, 0, 2). We use this fitted model to forecast the next data point by using the forecast.Arima function. The function is set at 99% confidence level. One can use the confidence level argument to enhance the model. We will be using the forecasted point estimate from the model. The “h” argument in the forecast function indicates the number of values that we want to forecast, in this case, the next day returns.

#We can use the summary function to confirm the results of the ARIMA model are within acceptable limits. In the last part, we append every forecasted return and the actual return to the forecasted returns series and the actual returns series respectively.


for (b in breakpoint:(nrow(stock)-1)) {

stock_train = stock[1:b, ]
stock_test = stock[(b+1):nrow(stock), ]

# Summary of the ARIMA model using the determined (p,d,q) parameters
fit = arima(stock_train, order = c(2, 0, 2),include.mean=FALSE)


# Forecasting the log returns
arima.forecast = forecast(fit, h = 1,level=99)

# Creating a series of forecasted returns for the forecasted period
forecasted_series = rbind(forecasted_series,arima.forecast$mean[1])
colnames(forecasted_series) = c("Forecasted")

# Creating a series of actual returns for the forecasted period
Actual_return = stock[(b+1),]
Actual_series = c(Actual_series,xts(Actual_return))
rm(Actual_return)

}

```

```{r}
arima(stock_train, order = c(0, 0, 1),include.mean = FALSE)

```




### Step 5: Make Predictions


```{r}
# Adjust the length of the Actual return series
Actual_series <- Actual_series[-1]

# Create a time series object of the forecasted series
forecasted_series <- xts(forecasted_series,index(Actual_series))

# Create a plot of the two return series - Actual versus Forecasted
plot(Actual_series, type = 'l', main = 'Actual Returns Vs Forecasted Returns')
lines(forecasted_series, lwd = 1.5, col = 'red')
legend('bottomright', c("Actual","Forecasted"), lty = c(1,1), lwd = c(1.5,1.5), col = c('black','red'))

# Create a table for the accuracy of the forecast
comparsion <- merge(Actual_series,forecasted_series)
comparsion$Accuracy <- sign(comparsion$Actual_series) == sign(comparsion$Forecasted)
print(comparsion)

# Compute the accuracy percentage metric
Accuracy_percentage <- sum(comparsion$Accuracy == 1)*100/length(comparsion$Accuracy)
print(Accuracy_percentage)

#draw the qqnorm & qqline
model <- arima(stock, order = c(0, 0, 1),include.mean = FALSE)
qqnorm(model$residuals)
qqline(model$residuals)

```


